### ISSUE TITLE
Postgres - Connection to insights-collector fails 

### ISSUE THREAD

**Issue by reach3r** [BlueMedoraPublic/new-relic-plugins#10]
Hello,

we are trying to evaluate the postgres plugin and while the reporting to the plugin page in NewRelic works fine, the connection to the insights collector fails.
Setup: The plugin is setup on the Postgres VM which has no direct connection to the internet, but needs a proxy. The necessary NewRelic domain is unlocked and is reachable through the proxy (tested via curl from the VM).

The weird thing is that the connection for the data on the plugin page is working, but the connection to the insights collector is not (before specifying the proxy in the <plugin dir>/config/newrelic.json no connection was working).

> [2017-04-19 10:30:25,140] ERROR com.bluemedora.newrelic.InsightsClient - Failed to POST events to Insights: org.apache.http.conn.HttpHostConnectException: Connect to insights-collector.newrelic.com:443 [insights-collector.newrelic.com/50.31.164.187] failed: Connection refused

```bash
root@dbhost:~# curl -i https://insights-collector.newrelic.com
HTTP/1.0 200 Connection established

HTTP/1.1 404 Not Found
Date: Wed, 19 Apr 2017 08:29:21 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html; charset=ISO-8859-1
Content-Length: 278

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

The newrelic.json:
```bash
root@dbhost:~/newrelic-npi# cat plugins/com.bluemedora.Postgres/newrelic_Postgres_plugin-2.1.2_20170106_212812/config/newrelic.json
{
  "license_key": "<our nr license key >",
  "insights_api_key": "<our newly created insights api key>",
  "insights_account_id": "<our insights account id>",
  "insights_use_ssl": true,
  "log_level": "warn",
  "proxy_host": "proxy.subdomain.company.tld",
  "proxy_port": "<proxyport>"
}
```

I tried to additionally specify the proxy as Java VM options in the init script, but that did not change anything.

My guess would be that the two metrics-endpoints use separate connections and for the insights one the proxy is not used properly, that's pure speculation though.

Could you shed some light on the issue?

Thanks in advance

**Comment by bluemedorasupport** [comment]
Hello, 
   
 Thanks for your email and apologies for the delayed response.  I have been attempting to re-create the issue and found that there is indeed an issue with the plugin sending information to Insights.  I have sent this to my dev team to fix the issue and am told there should be a new version of our plugin out sometime in the next two weeks that would have the issue fixed.  I will message back at this time so that we can get you back up and running with some new license keys. 
   
 Cheers, 
   
 Tim George 
 tim.george@bluemedora.com 
   
   
  
   
 
 
 
                 
         On Wed, 19 Apr at 11:44 AM
          ,  BlueMedoraPublic/new-relic-plugins <reply@reply.github.com>  wrote:
           Hello, 
 we are trying to evaluate the postgres plugin and while the reporting to the plugin page in NewRelic works fine, the connection to the insights collector fails. 
Setup: The plugin is setup on the Postgres VM which has no direct connection to the internet, but needs a proxy. The necessary NewRelic domain is unlocked and is reachable through the proxy (tested via curl from the VM). 
 The weird thing is that the connection for the data on the plugin page is working, but the connection to the insights collector is not (before specifying the proxy in the /config/newrelic.json no connection was working). 
 
 [2017-04-19 10:30:25,140] ERROR com.bluemedora.newrelic.InsightsClient - Failed to POST events to Insights: org.apache.http.conn.HttpHostConnectException: Connect to insights-collector.newrelic.com:443 [insights-collector.newrelic.com/50.31.164.187] failed: Connection refused 
 
  root@dbhost:~# curl -i https://insights-collector.newrelic.com
HTTP/1.0 200 Connection established

HTTP/1.1 404 Not Found
Date: Wed, 19 Apr 2017 08:29:21 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html; charset=ISO-8859-1
Content-Length: 278

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>  
 The newrelic.json: 
  root@dbhost:~/newrelic-npi# cat plugins/com.bluemedora.Postgres/newrelic_Postgres_plugin-2.1.2_20170106_212812/config/newrelic.json
{
  "license_key": "<our nr license key >",
  "insights_api_key": "<our newly created insights api key>",
  "insights_account_id": "<our insights account id>",
  "insights_use_ssl": true,
  "log_level": "warn",
  "proxy_host": "proxy.subdomain.company.tld",
  "proxy_port": "<proxyport>"
}  
 I tried to additionally specify the proxy as Java VM options in the init script, but that did not change anything. 
 My guess would be that the two metrics-endpoints use separate connections and for the insights one the proxy is not used properly, that's pure speculation though. 
 Could you shed some light on the issue? 
 Thanks in advance

**Comment by reach3r** [comment]
Hey there,

is there some update to be had? Unfortunately I have not yet heard back about any updates.

Best regards

**Comment by afearbm** [comment]
Hello reach3r,

The New Relic Plugin for PostgreSQL v 2.1.3 has been published. The issue you experienced with Insights using proxy settings has been fixed. Thank you for your patience while we were working on this for you.

Plugin/instructions for installing with NPI tool can be found here:
https://github.com/BlueMedoraPublic/new-relic-plugins/tree/master/postgresql

Andrew
andrew.fear@bluemedora.com

**Comment by reach3r** [comment]
I tested version 2.1.3 and it seems to work fine now. Thank you!
