### ISSUE TITLE
MySQL ERROR: Unexpected character

### ISSUE THREAD

**Issue by ricsdeol** [BlueMedoraPublic/new-relic-plugins#14]
Hi, i'm trying running MySQL plugin but  i have a problem  to start:
```
ERROR: Unexpected character (/) at position 1368.
Exception in thread "main" java.lang.NullPointerException
	at com.bluemedora.newrelic.Main.main(Main.java:23)
```
Thanks

**Comment by bluemedorasupport** [comment]
Hello, 
   
 Thanks for your email.  I can certainly help with getting to the bottom of your issue. 
 Looks like there is a configuration error in the JSON file for the plugin.  Were you trying to set up multiple instances?  The config file for one instance should only have about 1100 "positions" to go through.  Could you send me a screenshot of the config file (with username and passwords redacted, of course) to tim.george@bluemedora.com? 
   
 Cheers, 
   
 Tim George 
   
   
   
  
   
 
 
 
                 
         On Wed, 7 Jun at  3:18 PM
          ,  BlueMedoraPublic/new-relic-plugins <reply@reply.github.com>  wrote:
           Hi, i'm trying running MySql plugin but  i have a problem  to start: 
 ERROR: Unexpected character (/) at position 1368.
Exception in thread "main" java.lang.NullPointerException
	at com.bluemedora.newrelic.Main.main(Main.java:23)
 
 Thanks

**Comment by Joe-Klauza** [comment]
@ricsdeol check your `config/plugin.json` file for an errant forward slash (`/`) outside of quotation marks. See the following screenshot for an example of what to look for (highlighted in red):

![image](https://user-images.githubusercontent.com/13367199/26900846-948e16dc-4ba1-11e7-97bf-59119ab9732d.png)

If you're having trouble locating it, you can use a JSON validation tool like [JSONLint](https://jsonlint.com/) to point out the offending line.

**Comment by ricsdeol** [comment]
Hi @bluemedorasupport  had a coment with '//' at my config, i romoved and works!

Thanks for tip @Joe-Klauza

**Comment by bluemedorasupport** [comment]
Hi @ricsdeol, 
   
 I see what Joe had given some suggestions that worked out for you. Is everything up and collecting now?  Just wanted to make sure you have everything you need in order to put the plugin through it's paces. 
   
 Cheers, 
   
 Tim George 
   
   
  
   
 
 
 
                 
         On Wed, 7 Jun at  4:29 PM
          ,  Tim George <support@bluemedora.com>  wrote:
           
 
 
 Hello,
 
   
 Thanks for your email.  I can certainly help with getting to the bottom of your issue. 
 Looks like there is a configuration error in the JSON file for the plugin.  Were you trying to set up multiple instances?  The config file for one instance should only have about 1100 "positions" to go through.  Could you send me a screenshot of the config file (with username and passwords redacted, of course) to tim.george@bluemedora.com? 
   
 Cheers, 
   
 Tim George 
   
   
   
  
   
 
 
 
                 
         On Wed, 7 Jun at  3:18 PM
          ,  BlueMedoraPublic/new-relic-plugins <reply@reply.github.com>  wrote:
           Hi, i'm trying running MySql plugin but  i have a problem  to start: 
 ERROR: Unexpected character (/) at position 1368.
Exception in thread "main" java.lang.NullPointerException
	at com.bluemedora.newrelic.Main.main(Main.java:23)
 
 Thanks

**Comment by bluemedorasupport** [comment]
Hi @ricsdeol, 
   
 Just checking again to see if you had gotten the plugin.json file corrected and the plugin running.  Did you get it working? 
   
 Cheers, 
   
 Tim 
   
   
  
   
 
 
 
                 
         On Thu, 8 Jun at 10:50 AM
          ,  Tim George <support@bluemedora.com>  wrote:
           
 
 
 Hi @ricsdeol,
 
   
 I see what Joe had given some suggestions that worked out for you. Is everything up and collecting now?  Just wanted to make sure you have everything you need in order to put the plugin through it's paces. 
   
 Cheers, 
   
 Tim George 
   
   
  
   
 
 
 
                 
         On Wed, 7 Jun at  4:29 PM
          ,  Tim George <support@bluemedora.com>  wrote:
           
 
 
 Hello,
 
   
 Thanks for your email.  I can certainly help with getting to the bottom of your issue. 
 Looks like there is a configuration error in the JSON file for the plugin.  Were you trying to set up multiple instances?  The config file for one instance should only have about 1100 "positions" to go through.  Could you send me a screenshot of the config file (with username and passwords redacted, of course) to tim.george@bluemedora.com? 
   
 Cheers, 
   
 Tim George 
   
   
   
  
   
 
 
 
                 
         On Wed, 7 Jun at  3:18 PM
          ,  BlueMedoraPublic/new-relic-plugins <reply@reply.github.com>  wrote:
           Hi, i'm trying running MySql plugin but  i have a problem  to start: 
 ERROR: Unexpected character (/) at position 1368.
Exception in thread "main" java.lang.NullPointerException
	at com.bluemedora.newrelic.Main.main(Main.java:23)
 
 Thanks
