### ISSUE TITLE
Does this plugin report on lock waits for postgres?

### ISSUE THREAD

**Issue by mandragorn** [BlueMedoraPublic/new-relic-plugins#16]

**Comment by bluemedorasupport** [comment]
Hello, 
   
 Thanks for your interest in our PostgreSQL plugin.  I wanted to send over a list of the metrics we can pull from New Relic Insights to create custom dashboards with so that you can see what we pull around locks.  HERE is a link where you can find this information.  As far as PostgreSQL, how many instances are you looking to monitor? 
   
 Cheers, 
   
 Tim George

**Comment by timgeorge36** [comment]
Looks like the link I tried to put in the last message didn't work.  Below is the full link to the list of metrics:
[https://github.com/BlueMedoraPublic/new-relic-plugins/blob/master/postgresql/metrics.md](
https://github.com/BlueMedoraPublic/new-relic-plugins/blob/master/postgresql/metrics.md)

**Comment by mandragorn** [comment]
awesome, thank you.  For some reason I didn't find that page and the pages I was looking at weren't clear.

The bottom of this page is where I was looking (it doesn't mention locks, just deadlocks).

https://github.com/BlueMedoraPublic/new-relic-plugins/tree/master/postgresql
