### ISSUE TITLE
Cassandra plugin username/password required ?

### ISSUE THREAD

**Issue by mavericknomad** [BlueMedoraPublic/new-relic-plugins#9]
Hi,

I am doing POC of BlueMedora Cassandra plugin as I think it is very promising. There is one issue I am facing after doing installation.
We haven't enabled JMX authentication so I left below fields as it is:
############################
 "username": "your_value_here",
      "password": "your_value_here",
############################

The plugin is disconnecting as seen from below error:
#####################
[2016-12-21 12:06:39,595] DEBUG com.bluemedora.newrelic.ExUnoAgent - apache_cassandra_dp_1.0.0_ga_20161213_145633.com.bluemedora.dataprovider.jmx.connection.JmxConnection: Entering disconnect()
#####################

could you please help us to resolve this issue ?

**Comment by bluemedorasupport** [comment]
Hi, 
   
 I just wanted to send a quick email to let you know that I am looking into this issue with my dev team to see how we can get this plugin up and running for you.  We are working on getting a resolution so that you can get a POC fully vetted within your New Relic environment. 
   
 In the meantime, could you send me some debug level logs so we can find out exactly where the issue begins? 
   
 Cheers, 
   
 Tim George 
   
   
  
   
 
 
 
                 
         On Wed, 21 Dec, 2016 at 12:07 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           Hi, 
 I am doing POC of BlueMedora Cassandra plugin as I think it is very promising. There is one issue I am facing after doing installation. 
We haven't enabled JMX authentication so I left below fields as it is: 
############################ 
"username": "your_value_here", 
"password": "your_value_here", 
############################ 
 The plugin is disconnecting as seen from below error: 
##################### 
[2016-12-21 12:06:39,595] DEBUG com.bluemedora.newrelic.ExUnoAgent - apache_cassandra_dp_1.0.0_ga_20161213_145633.com.bluemedora.dataprovider.jmx.connection.JmxConnection: Entering disconnect() 
##################### 
 could you please help us to resolve this issue ?

**Comment by mavericknomad** [comment]
Hi Bluemedora team,

Thanks for your response.

Please find attached debug logs.

Thanks,
Santosh

**Comment by bluemedorasupport** [comment]
Hi Santosh, 
   
 I received your reply, but did no see any logs attached.  If you would like to email me directly, my address is tim.george@bluemedora.com.  I have one of our developers standing by. 
   
 Cheers, 
   
 Tim 
   
   
  
   
 
 
 
                 
         On Tue, 3 Jan at  5:33 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           Hi Bluemedora team, 
 
Thanks for your response. 
 
Please find attached debug logs. 
 
Thanks, 
Santosh

**Comment by mavericknomad** [comment]
Sending zip file again. Filename is newrelic_plugin.zip

Please check now.

Thanks,
Santosh

**Comment by bluemedorasupport** [comment]
Hi , 
   
 I just wanted to send a quick email to let you know we are working on the issue you have been having with our Cassandra plugin for New Relic.  The developers who worked on that have been looking into the logs and trying to recreate exactly what you are seeing.   
   
 That team did have a question, however.  Do you know what version of Cassandra you are using? 
   
 Cheers, 
   
 Tim 
   
   
  
   
 
 
 
                 
         On Tue, 3 Jan at  8:46 AM
          ,  Blue Medora Support <support@bluemedora.com>  wrote:
           
 
 
 Hi,
 
   
 I just wanted to send a quick email to let you know that I am looking into this issue with my dev team to see how we can get this plugin up and running for you.  We are working on getting a resolution so that you can get a POC fully vetted within your New Relic environment. 
   
 In the meantime, could you send me some debug level logs so we can find out exactly where the issue begins? 
   
 Cheers, 
   
 Tim George 
   
   
  
   
 
 
 
                 
         On Wed, 21 Dec, 2016 at 12:07 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           Hi, 
 I am doing POC of BlueMedora Cassandra plugin as I think it is very promising. There is one issue I am facing after doing installation. 
We haven't enabled JMX authentication so I left below fields as it is: 
############################ 
"username": "your_value_here", 
"password": "your_value_here", 
############################ 
 The plugin is disconnecting as seen from below error: 
##################### 
[2016-12-21 12:06:39,595] DEBUG com.bluemedora.newrelic.ExUnoAgent - apache_cassandra_dp_1.0.0_ga_20161213_145633.com.bluemedora.dataprovider.jmx.connection.JmxConnection: Entering disconnect() 
##################### 
 could you please help us to resolve this issue ?

**Comment by mavericknomad** [comment]
Hi,

Sorry for late reply. Here is the cassandra and dse version:
Cassandra 2.1.15.1403 
DSE 4.8.9

**Comment by bluemedorasupport** [comment]
Hi, 
   
 I just wanted to send a quick email to let you know that I was still working on this issue with my support team and will let you know when I get an answer for you. 
   
 Cheers, 
   
 Tim George 
   
   
  
   
 
 
 
                 
         On Wed, 4 Jan at  9:39 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           Sending zip file again. Filename is newrelic_plugin.zip 
 
Please check now. 
 
Thanks, 
Santosh

**Comment by mavericknomad** [comment]
any update on this issue ?

**Comment by mavericknomad** [comment]
Hi Bluemedora team,

Any update on this issue ?

**Comment by mavericknomad** [comment]
Please mark this issue as closed.

I removed username/password fields from plugin.json to resolve the issue.
